apiVersion: kudev.io/v1alpha1
kind: DeploymentConfig
metadata:
  name: myapp
spec:
  # Container image name (without registry)
  imageName: myapp

  # Dockerfile location relative to project root
  dockerfilePath: ./Dockerfile

  # Target Kubernetes namespace
  namespace: default

  # Number of replicas
  replicas: 1

  # Local port for port forwarding
  localPort: 8080

  # Container port
  servicePort: 8080

  # Environment variables
  env:
    - name: LOG_LEVEL
      value: info
    - name: DEBUG
      value: "false"

  # Optional: Kubeconfig context to pin
  kubeContext: docker-desktop

  # Optional: Files to exclude from build hash
  buildContextExclusions:
    - .git
    - node_modules
    - vendor